#!/usr/bin/env python3

import sys
from subprocess import call

def help():
	print ("Temporary usage: ")
	print ("\t./vype vype14-source.file {tree|gui}") 
	print ("\t./vype -h")

def main():

	if len(sys.argv) == 2 and sys.argv[1] == "-h":
		help()
		return
	elif len(sys.argv) != 3:
		print ("Incorrect argumnets!")
		help()
		return
	else:
		grunClass = "org.antlr.v4.runtime.misc.TestRig"
		lexerParser = "VYPe2014"
		method = "compilationUnit"
		visualization = sys.argv[2]
		call([ "java", grunClass, lexerParser, method, "-" + visualization, sys.argv[1] ])


if __name__ == "__main__":
    main()